# Generated by Django 3.1 on 2020-10-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('liveurl', models.TextField(blank=True, null=True)),
                ('livetime', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('s_explain', models.TextField()),
                ('explain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MultiFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(null=True, verbose_name='첨부파일명')),
                ('upload_files', models.FileField(blank=True, null=True, upload_to='multi_files', verbose_name='파일')),
                ('itemid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OneFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(null=True, verbose_name='첨부파일명')),
                ('upload_files', models.FileField(blank=True, null=True, upload_to='one_files/', verbose_name='파일')),
                ('itemid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionname', models.TextField()),
                ('option', models.TextField()),
                ('option_num', models.TextField()),
                ('itemid', models.IntegerField()),
            ],
        ),
    ]
